version: '3.8'

services:
  app:
    container_name: meal-organizer-backend
    image: meal-organizer-backend:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - ./db/database.sqlite:/app/database.sqlite
